template_path: nextflow-tower-secret.yaml
stack_name: nextflow-tower-secret
dependencies:
  - prod/workflows-kms-key.yaml
parameters:
  KmsKeyAlias: !stack_output_external workflows-infra-kms-key::Alias
