template_path: remote/vpc.yaml
stack_name: nextflow-vpc
parameters:
  VpcName: nextflow-vpc
  VpcSubnetPrefix: "10.41"
hooks:
  before_launch:
    - !cmd "wget {{stack_group_config.aws_infra_templates_root_url}}/v0.2.3/templates/vpc.yaml -N -P templates/remote"
