default_language_version:
    python: python3.10
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.32.0
    hooks:
      - id: yamllint
  - repo: https://github.com/awslabs/cfn-python-lint
    rev: v0.82.0
    hooks:
      - id: cfn-python-lint
        files: templates/.*\.(json|yml|yaml)$
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.4
    hooks:
      - id: remove-tabs
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.6.0
    hooks:
      - id: mypy
        args: [--implicit-optional]
  - repo: https://github.com/psf/black
    rev: 23.10.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        args: ["--max-line-length", "88"]
  - repo: https://github.com/sirosen/check-jsonschema
    rev: 0.27.0
    hooks:
      - id: check-github-workflows
      - id: check-github-actions
  - repo: https://github.com/aristanetworks/j2lint.git
    rev: v1.1.0
    hooks:
      - id: j2lint
        args: [--ignore, S6, --]
