template:
  path: nextflow-efs-file-system.yaml
stack_name: nextflow-efs-file-system
dependencies:
  - infra-prod/nextflow-vpc.yaml
  - infra-prod/nextflow-ecs-security-group.yaml
  - infra-prod/nextflow-tower-config-bucket.yaml
  - infra-prod/nextflow-ecs-cluster.yaml

parameters:
  VpcId: !stack_output_external nextflow-vpc::VPCId
  SubnetId: !stack_output_external nextflow-ecs-cluster::EcsAutoScalingGroupSubnetId
  EcsSecurityGroupId: !stack_output_external nextflow-ecs-security-group::SecurityGroupId
  NextflowTowerConfigBucketArn: !stack_output_external nextflow-tower-config::BucketArn
  ThroughputMode: provisioned
  ProvisionedThroughputInMibps: "1024"

stack_tags:
  {{stack_group_config.default_stack_tags}}
