template:
  path: nextflow-launch.yaml
stack_name: nextflow-launch

dependencies:
  - infra-dev/nextflow-ecs-cluster

parameters:
  EcsSecurityGroupId: !stack_output_external nextflow-ecs-security-group::SecurityGroupId
  SubnetId: !stack_output_external nextflow-vpc::PrivateSubnet

stack_tags:
  {{stack_group_config.default_stack_tags}}
