template:
  path: tower-project.j2
stack_name: iatlas-project

stack_tags:
  Department: DNT
  Project: iAtlas
  OwnerEmail: thomas.yu@sagebase.org
  CostCenter: iAtlas 3 / 314900

parameters:
  S3ReadWriteAccessArns:
    - "{{stack_group_config.tower_viewer_arn_prefix}}/brad.macdonald@sagebase.org"
    - "{{stack_group_config.tower_viewer_arn_prefix}}/thomas.yu@sagebase.org"
    - "{{stack_group_config.tower_viewer_arn_prefix}}/adam.taylor@sagebase.org"
    - "{{stack_group_config.tower_viewer_arn_prefix}}/james.eddy@sagebase.org"
    # The following roles don't exist since the users are not Sage employees.
    # However, this will ensure that they are added to the Tower workspace
    # until we find a permanent solution for listing external users.
    - "{{stack_group_config.tower_viewer_arn_prefix}}/benjamin_vincent@med.unc.edu"
    - "{{stack_group_config.tower_viewer_arn_prefix}}/dbortone@email.unc.edu"
    - "{{stack_group_config.tower_viewer_arn_prefix}}/steven_vensko@med.unc.edu"
  AccountAdminArns:
    - "{{stack_group_config.sso_admin_role.arn}}"
    - !stack_output_external workflows-nextflow-ci-service-account::ServiceRoleArn
    - !stack_output_external sagebase-github-oidc-workflows-prod-nextflow-infra::ProviderRoleArn
  TemplateRootUrl: "https://{{stack_group_config.admincentral_cf_bucket}}.s3.amazonaws.com"
  TowerForgePolicyArn: !stack_output_external nextflow-forge-iam-policy::NextFlowForgePolicyArn
  TowerLaunchPolicyArn: !stack_output_external nextflow-launch-iam-policy::NextFlowLaunchPolicyArn

dependencies:
  - common/nextflow-forge-iam-policy.yaml
  - common/nextflow-launch-iam-policy.yaml
