stack_name: ntap-cnf-cell-project

stack_tags:
  Department: SCCE
  Project: Neurofibromatosis
  OwnerEmail: robert.allaway@sagebase.org
  CostCenter: NTAP-JHU / 30110

parameters:

  S3ReadWriteAccessArns:
    - '{{stack_group_config.tower_viewer_arn_prefix}}/robert.allaway@sagebase.org'
    - '{{stack_group_config.tower_viewer_arn_prefix}}/jineta.banerjee@sagebase.org'
    - '{{stack_group_config.tower_viewer_arn_prefix}}/thomas.yu@sagebase.org'

  # (Optional) Step 6: Uncomment and update the following lines to change the S3 bucket lifecycle configuration,
  #                    which cannot be changed as long as 'AllowSynapseIndexing' is enabled (default)
  # AllowSynapseIndexing: Disabled
  # EnableDataLifeCycle: Enabled
  # LifecycleDataTransition: '30'  # In days
  # LifecycleDataStorageClass: INTELLIGENT_TIERING

  # (Optional) Step 7: Uncomment and update the following line to change when objects are deleted automatically
  # LifecycleDataExpiration: '730'  # In days (i.e., 2 years)

  # DO NOT EDIT ANYTHING BELOW THIS LINE ------------------------------------------------------------------------

  AccountAdminArns:
    - '{{stack_group_config.sso_admin_role.arn}}'
    - !stack_output_external workflows-nextflow-ci-service-account::ServiceRoleArn
    - !stack_output_external sagebase-github-oidc-workflows-prod-nextflow-infra::ProviderRoleArn
  TemplateRootUrl: 'https://{{stack_group_config.admincentral_cf_bucket}}.s3.amazonaws.com'
  TowerForgePolicyArn: !stack_output_external nextflow-forge-iam-policy::NextFlowForgePolicyArn
  TowerLaunchPolicyArn: !stack_output_external nextflow-launch-iam-policy::NextFlowLaunchPolicyArn

template:
  path: tower-project.j2

dependencies:
  - common/nextflow-forge-iam-policy.yaml
  - common/nextflow-launch-iam-policy.yaml
