template_path: workflows-kms-key.yaml
stack_name: workflows-infra-kms-key
parameters:
  TemplateRootUrl: 'https://{{stack_group_config.admincentral_cf_bucket}}.s3.amazonaws.com'
  AccountAdminArns:
    - {{stack_group_config.sso_admin_role.arn}}
    - !stack_output_external workflows-nextflow-ci-service-account::ServiceRoleArn
stack_tags:
  Department: IBC
  Project: Infrastructure
  OwnerEmail: nextflow-admins@sagebase.org
