AWSTemplateFormatVersion: '2010-09-09'
Description: Shared resources Nextflow Tower ECS Service

Resources:
  EcsServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service:
              - ecs.amazonaws.com
          Action:
            - sts:AssumeRole
      Path: /
      Policies:
      - PolicyName: ecs-service
        PolicyDocument:
          Statement:
          - Effect: Allow
            Action:
              - elasticloadbalancing:DeregisterInstancesFromLoadBalancer
              - elasticloadbalancing:DeregisterTargets
              - elasticloadbalancing:Describe*
              - elasticloadbalancing:RegisterInstancesWithLoadBalancer
              - elasticloadbalancing:RegisterTargets
              - ec2:Describe*
              - ec2:AuthorizeSecurityGroupIngress
            Resource: '*'

Outputs:
  EcsServiceRoleArn:
    Value: !GetAtt EcsServiceRole.Arn
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-EcsServiceRoleArn'
