AWSTemplateFormatVersion: '2010-09-09'
Description: Elasticache cluster for Nextflow Tower
Parameters:
  VpcId:
    Description: ID of VPC
    Type: AWS::EC2::VPC::Id

  VpcSubnetIDs:
    Description: The VPC subnet IDs.
    Type: List<AWS::EC2::Subnet::Id>

  EcsSecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
    Description: Security group ID for ECS cluster to grant database access

Resources:
  ElasticacheSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Elasticache Security Group
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - SourceSecurityGroupId: !Ref EcsSecurityGroupId
          IpProtocol: tcp
          FromPort: 6379
          ToPort: 6379
  ElasticacheSubnetGroup:
    Type: AWS::ElastiCache::SubnetGroup
    Properties:
      Description: Elasticache subnet group
      SubnetIds: !Ref VpcSubnetIDs
  ElasticacheCluster:
    Type: AWS::ElastiCache::CacheCluster
    Properties:
      CacheNodeType: cache.r6g.large
      Engine: redis
      NumCacheNodes: "1"
      VpcSecurityGroupIds:
        - !GetAtt ElasticacheSecurityGroup.GroupId
      CacheSubnetGroupName: !Ref ElasticacheSubnetGroup

Outputs:

  RedisEndpointAddress:
    Value: !GetAtt ElasticacheCluster.RedisEndpoint.Address
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-RedisEndpointAddress'

  RedisEndpointPort:
    Value: !GetAtt ElasticacheCluster.RedisEndpoint.Port
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-RedisEndpointPort'

  RedisEndpoint:
    Value: !Sub 'redis://${ElasticacheCluster.RedisEndpoint.Address}:${ElasticacheCluster.RedisEndpoint.Port}'
