name: main

on:
  pull_request:
    branches: [ '*' ]
  push:
    paths-ignore:
      - '**.md'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up python and cache
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pipenv'
      - name: Install pipenv
        run: curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python
      - name: Install dependencies
        run: pipenv install --dev
      - name: Run pre-commit linters
        uses: pre-commit/action@v3.0.0
      # verify jinja templates
      - name: Install jinja libraries
        run: |
          python -m pip install --upgrade jinja2==3.0.1
      - name: Install jinja linter tool
        run: git clone --single-branch https://github.com/drm/jinja2-lint.git /tmp/jinja2-lint && pushd /tmp/jinja2-lint && git checkout 75dcd5a
      - name: Lint jinja templates
        run: find . -type f -name "*.j2" -exec /tmp/jinja2-lint/j2lint.py '{}' +

  deploy-dev:
    if: github.ref == 'refs/heads/dev'
    needs:
      - validate
    uses: "./.github/workflows/rw-deploy.yaml"
    secrets: inherit
    with:
      job-environment: "workflows-nextflow-dev"
      sceptre-suffix: "dev"
      tower-url: "https://tower-dev.sagebionetworks.org"

  deploy-prod:
    if: github.ref == 'refs/heads/prod'
    needs:
      - validate
    uses: "./.github/workflows/rw-deploy.yaml"
    secrets: inherit
    with:
      job-environment: "workflows-nextflow-prod"
      sceptre-suffix: "prod"
      tower-url: "https://tower.sagebionetworks.org"

  deploy-ampad:
    if: github.ref == 'refs/heads/prod'
    needs: deploy-prod
    uses: "./.github/workflows/rw-deploy.yaml"
    secrets: inherit
    with:
      job-environment: "org-sagebase-strides-ampad-workflows"
      sceptre-suffix: "ampad"
      tower-url: "https://tower.sagebionetworks.org"
